name: Merge Pull Request

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  storybook:
    runs-on: ubuntu-latest
    name: Publish Storybook
    if: github.event.pull_request.merged == true

    steps:
      - uses: danielchabr/pr-has-one-of-labels@master
        id: label_check
        with:
          hasSome: docs,stories
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: yarn install
      - name: Deploy storybook to Github Pages
        run: yarn deploy-storybook --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
  packages:
      runs-on: ubuntu-latest
      name: Publish Packages
      if: github.event.pull_request.merged == true

      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: "12.x"
        - name: Setup git
          run: |
            git config --global user.name ${{github.event.pusher.name}}
            git config --global user.email ${{github.event.pusher.email}}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - uses: danielchabr/pr-has-one-of-labels@master
          id: label_check
          with:
            hasAll: packages
        - run: yarn install
        - run: yarn build
        - name: Publish patch Packages
          if: contains(github.event.pull_request.title,'fix') == true
          run: yarn lerna publish patch --yes
        - name: Publish minor Packages
          if: contains(github.event.pull_request.title,'feat') == true
          run: yarn lerna publish minor --yes
