name: Merge Pull Request

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  storybook:
    runs-on: ubuntu-latest
    name: Publish Storybook
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

    steps:
      - uses: danielchabr/pr-has-one-of-labels@master
        id: label_check
        with:
          hasSome: docs, stories
      - name: Verify Label
        if: contains(${{ steps.label_check.outputs }}, 'passed') == false
        run: exit 1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: yarn build-storybook
      - run: yarn deploy-storybook
