name: Merge Pull Request

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  storybook:
    runs-on: ubuntu-latest
    name: Publish Storybook
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

    steps:
      - uses: danielchabr/pr-has-one-of-labels@master
        id: label_check
        with:
          hasSome: docs, stories
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: yarn install
      - name: Deploy storybook to Github Pages
        run: npx deploy-storybook -- -ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
